In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# File to Load
weather_data_to_load = "monthly_mean_temps.csv"
state_data_to_load = "State_Names.csv"

# Read the weahter and state Data
weather_df = pd.read_csv(weather_data_to_load, low_memory=False)
state_df = pd.read_csv(state_data_to_load, low_memory=False)

In [3]:
weather_df.head()

,City,State,January,February,March,April,May,June,July,August,September,October,November,December,Annual
0,BIRMINGHAM AP,AL,43.8,47.7,55.2,62.5,70.6,77.7,81.1,80.7,74.7,64.1,54.4,46.1,63.2
1,HUNTSVILLE,AL,41.5,45.7,53.5,61.8,70.3,77.7,80.6,80.1,73.7,62.8,52.7,43.9,62.0
2,MOBILE,AL,50.2,53.5,59.8,66.4,73.8,79.8,82.1,82.1,78.5,69.2,60.0,52.6,67.3
3,MONTGOMERY,AL,46.6,50.5,57.5,64.1,72.4,79.0,81.8,81.5,76.3,65.9,56.5,48.5,65.1
4,ANCHORAGE,AK,17.1,20.2,26.6,36.8,47.8,55.2,58.8,56.7,48.6,34.8,22.2,19.0,37.0

In [4]:
state_df.head()

  US State Name State Code
0       Alabama         AL
1        Alaska         AK
2       Arizona         AZ
3      Arkansas         AR
4    California         CA

In [5]:
# Combine the data into a single dataset to get the full name of each state
merge_table = pd.merge(weather_df, state_df, left_on="State",right_on="State Code", how="left")
merge_table

,City,State,January,February,March,April,May,June,July,August,September,October,November,December,Annual,US State Name,State Code
0,BIRMINGHAM AP,AL,43.8,47.7,55.2,62.5,70.6,77.7,81.1,80.7,74.7,64.1,54.4,46.1,63.2,Alabama,AL
1,HUNTSVILLE,AL,41.5,45.7,53.5,61.8,70.3,77.7,80.6,80.1,73.7,62.8,52.7,43.9,62.0,Alabama,AL
2,MOBILE,AL,50.2,53.5,59.8,66.4,73.8,79.8,82.1,82.1,78.5,69.2,60.0,52.6,67.3,Alabama,AL
3,MONTGOMERY,AL,46.6,50.5,57.5,64.1,72.4,79.0,81.8,81.5,76.3,65.9,56.5,48.5,65.1,Alabama,AL
4,ANCHORAGE,AK,17.1,20.2,26.6,36.8,47.8,55.2,58.8,56.7,48.6,34.8,22.2,19.0,37.0,Alaska,AK
5,ANNETTE,AK,37.0,37.7,39.7,44.2,50.2,55.1,58.6,58.9,53.8,46.7,40.0,37.1,46.6,Alaska,AK
6,BARROW,AK,-13.4,-14.2,-12.7,1.8,21.1,35.6,40.9,39.0,32.1,17.2,0.7,-7.8,11.7,Alaska,AK
7,BETHEL,AK,6.6,11.1,15.2,26.9,41.9,52.5,56.1,53.5,45.6,30.3,17.4,10.4,30.6,Alaska,AK
8,BETTLES,AK,-10.0,-5.0,4.4,23.3,44.4,58.5,59.7,52.5,40.6,18.9,-1.0,-5.7,23.4,Alaska,AK
9,BIG DELTA,AK,-1.0,4.9,14.1,32.2,47.6,57.6,60.2,54.8,43.9,24.1,6.2,2.1,28.9,Alaska,AK
10,COLD BAY,AK,28.2,29.0,30.1,34.0,40.3,46.3,50.9,52.1,48.1,40.4,34.5,31.1,38.8,Alaska,AK
11,FAIRBANKS,AK,-7.9,-1.3,11.4,32.5,49.4,60.4,62.5,56.1,44.9,24.2,2.6,-4.1,27.6,Alaska,AK
12,GULKANA,AK,-2.9,5.5,15.6,31.8,45.2,54.4,57.6,53.5,43.3,26.6,5.8,0.4,28.1,Alaska,AK
13,HOMER,AK,24.8,26.2,29.9,37.0,44.5,50.6,54.6,53.9,48.1,38.1,29.5,27.1,38.7,Alaska,AK
14,JUNEAU,AK,28.3,30.1,33.8,40.8,48.6,54.6,56.9,55.9,50.0,42.4,33.4,29.9,42.1,Alaska,AK
15,KING SALMON,AK,16.2,18.8,24.1,33.7,44.2,51.5,55.5,54.6,47.6,33.5,22.9,18.6,35.1,Alaska,AK
16,KODIAK,AK,30.5,30.8,32.8,37.6,44.3,49.7,54.5,55.2,49.4,40.5,33.9,31.2,40.9,Alaska,AK
17,KOTZEBUE,AK,-2.8,-0.8,1.1,13.3,31.9,45.7,54.6,51.7,42.3,24.3,9.1,2.3,22.7,Alaska,AK
18,MCGRATH,AK,-6.5,1.4,11.6,29.7,46.7,57.4,60.0,54.6,44.6,25.1,5.5,-3.2,27.2,Alaska,AK
19,NOME,AK,5.2,7.4,10.3,20.5,36.8,47.8,52.2,50.1,42.8,28.7,16.9,9.5,27.4,Alaska,AK
20,ST. PAUL ISLAND,AK,25.1,24.4,24.8,29.2,36.2,42.4,47.2,48.8,45.3,38.6,33.0,28.9,35.3,Alaska,AK
21,TALKEETNA,AK,14.2,18.1,24.9,35.9,47.8,57.0,60.1,56.7,47.5,33.2,19.5,16.0,35.9,Alaska,AK
22,VALDEZ,AK,21.8,23.3,28.7,37.0,45.6,51.6,54.1,52.7,47.2,36.7,27.8,24.8,37.6,Alaska,AK
23,YAKUTAT,AK,28.1,29.7,32.0,37.8,44.7,50.8,54.3,53.8,48.4,41.0,32.3,29.6,40.2,Alaska,AK
24,FLAGSTAFF,AZ,29.9,32.1,37.0,43.3,51.6,59.9,66.1,64.2,57.4,46.8,36.7,29.6,46.2,Arizona,AZ
25,PHOENIX,AZ,56.4,59.7,65.2,72.7,82.1,90.8,94.8,93.6,88.4,76.7,64.1,55.4,75.0,Arizona,AZ
26,TUCSON,AZ,52.7,54.7,59.9,66.5,75.9,84.5,86.8,84.7,81.3,70.6,59.9,52.4,69.2,Arizona,AZ
27,WINSLOW,AZ,35.2,40.3,47.0,54.3,63.6,72.7,78.2,76.0,68.7,56.3,44.0,34.6,55.9,Arizona,AZ
28,YUMA,AZ,55.6,58.5,63.1,70.2,78.1,86.5,92.5,91.9,86.3,74.1,61.9,54.2,72.7,Arizona,AZ
29,FORT SMITH,AR,39.4,44.2,52.9,61.6,69.9,77.8,82.3,82.1,73.9,62.8,51.6,41.3,61.7,Arkansas,AR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,OLYMPIA,WA,39.8,41.0,44.5,48.3,54.2,59.1,63.8,64.1,58.9,50.3,43.3,38.4,50.5,Washington,WA
253,QUILLAYUTE,WA,41.6,42.1,44.1,46.7,51.3,55.3,58.9,59.6,56.6,50.0,44.2,40.4,49.2,Washington,WA
254,SEATTLE C.O.,WA,43.0,44.3,47.6,51.4,57.3,62.0,66.2,66.6,61.9,53.7,46.5,41.4,53.5,Washington,WA
255,SEATTLE SEA-TAC AP,WA,42.0,43.4,46.5,50.3,56.0,60.9,65.7,66.1,61.3,52.8,45.4,40.6,52.6,Washington,WA
256,SPOKANE,WA,29.5,33.0,40.2,47.0,55.1,62.1,69.8,69.3,60.2,47.6,35.7,27.4,48.1,Washington,WA
257,WALLA WALLA,WA,35.5,39.1,46.3,52.2,59.4,66.5,75.0,74.2,65.2,53.3,41.8,33.4,53.5,Washington,WA
258,YAKIMA,WA,31.0,36.1,43.2,49.1,57.1,63.9,70.6,69.3,60.8,49.0,37.3,28.5,49.7,Washington,WA
259,BECKLEY,WV,31.1,34.4,42.1,52.1,59.8,67.4,70.6,69.7,63.2,53.2,43.9,34.2,51.8,West Virginia,WV
260,CHARLESTON,WV,34.4,37.7,45.8,56.1,63.7,71.9,75.4,74.3,67.3,56.5,47.0,37.4,55.6,West Virginia,WV
261,ELKINS,WV,29.2,32.2,39.8,49.7,58.1,66.3,70.0,69.1,62.2,51.2,41.9,32.5,50.2,West Virginia,WV
262,HUNTINGTON,WV,33.7,37.2,45.9,56.2,64.0,72.1,75.7,74.8,67.6,56.6,46.8,37.0,55.6,West Virginia,WV
263,GREEN BAY,WI,16.6,20.3,30.8,43.9,55.0,64.7,69.1,67.3,59.2,47.1,34.6,21.5,44.2,Wisconsin,WI
264,LA CROSSE,WI,17.4,22.5,34.5,48.6,59.7,69.2,73.7,71.4,62.8,50.2,35.9,21.6,47.3,Wisconsin,WI
265,MADISON,WI,18.8,23.1,34.0,46.6,57.3,67.0,71.3,69.2,61.0,48.9,36.2,23.0,46.4,Wisconsin,WI
266,MILWAUKEE,WI,22.3,25.9,35.0,45.6,55.7,66.2,71.8,70.7,63.1,51.3,39.0,26.5,47.8,Wisconsin,WI
267,CASPER,WY,24.7,26.7,35.2,42.7,52.2,62.2,70.5,69.0,57.9,45.2,33.2,23.8,45.3,Wyoming,WY
268,CHEYENNE,WY,28.8,29.6,35.9,42.8,52.4,62.1,69.4,67.6,58.2,46.3,35.3,27.7,46.3,Wyoming,WY
269,LANDER,WY,23.0,25.0,34.9,42.9,52.7,62.2,70.4,69.0,59.0,45.6,32.8,23.1,45.1,Wyoming,WY
270,SHERIDAN,WY,23.8,26.6,35.2,43.6,52.5,61.6,70.0,69.0,57.9,45.5,32.7,22.9,45.1,Wyoming,WY
271,GUAM,PC,80.2,79.9,80.7,81.9,82.6,82.6,81.9,81.4,81.4,81.7,81.8,81.2,81.4,NaN,NaN
272,JOHNSTON ISLAND,PC,78.3,78.4,78.6,79.5,80.7,82.2,83.0,83.6,83.4,82.5,80.6,79.1,80.8,NaN,NaN
273,KOROR,PC,81.4,81.3,81.7,82.3,82.4,81.6,81.3,81.5,81.7,82.0,82.4,81.9,81.8,NaN,NaN
274,KWAJALEIN-MARSHALL IS.,PC,81.7,81.9,82.3,82.5,82.8,82.5,82.3,82.5,82.6,82.5,82.3,82.0,82.3,NaN,NaN
275,MAJURO-MARSHALL IS,PC,81.7,81.9,82.1,82.1,82.3,82.1,82.1,82.3,82.4,82.4,82.2,81.8,82.1,NaN,NaN
276,PAGO PAGO-AMER SAMOA,PC,82.5,82.7,82.8,82.4,81.7,80.9,80.3,80.3,81.0,81.4,82.0,82.3,81.7,NaN,NaN
277,POHNPEI-CAROLINE IS.,PC,80.7,80.9,81.1,81.1,81.2,81.0,80.8,81.0,80.8,80.8,80.9,80.7,80.9,NaN,NaN
278,CHUUK E. CAROLINE IS.,PC,81.2,81.3,81.6,81.8,82.1,81.8,81.5,81.3,81.5,81.5,81.8,81.6,81.6,NaN,NaN
279,WAKE ISLAND,PC,78.7,78.1,78.6,79.7,81.2,82.9,83.4,83.6,83.7,82.9,81.4,79.9,81.2,NaN,NaN
280,YAP-W CAROLINE IS.,PC,82.2,82.2,82.6,83.4,83.7,83.0,82.5,82.4,82.6,82.8,82.9,82.6,82.7,NaN,NaN
281,SAN JUAN,PR,77.6,77.9,78.9,80.3,81.9,83.3,83.4,83.7,83.5,82.6,80.6,78.7,81.0,NaN,NaN

In [6]:
# group by state
grouped_df =merge_table.groupby(['US State Name','State'])
grouped_df
# set a blank list to contain monthly data later
frames=[]

for month in ["January","February","March","April","May","June","July","August","September","October","November","December"]:
    temp=grouped_df[month].mean()
    monthly_data = pd.DataFrame({
    "Month": month,
    "Avg_temp": temp})
    frames.append(monthly_data)

# consolidate all monthly data in frames list 
main_table = pd.concat(frames)
main_table

                         Month   Avg_temp
US State Name  State
Alabama        AL      January  45.525000
Alaska         AK      January  11.930000
Arizona        AZ      January  45.960000
Arkansas       AR      January  40.433333
California     CA      January  49.237500
Colorado       CO      January  27.080000
Connecticut    CT      January  28.600000
Delaware       DE      January  32.400000
Florida        FL      January  59.276923
Georgia        GA      January  46.100000
Hawaii         HI      January  71.225000
Idaho          ID      January  30.400000
Illinois       IL      January  23.900000
Indiana        IN      January  27.475000
Iowa           IA      January  19.650000
Kansas         KS      January  30.460000
Kentucky       KY      January  34.225000
Louisiana      LA      January  50.825000
Maine          ME      January  16.250000
Maryland       MD      January  32.900000
Massachusetts  MA      January  26.200000
Michigan       MI      January  21.411111
Minnesota      MN      January  11.500000
Mississippi    MS      January  44.366667
Missouri       MO      January  31.275000
Montana        MT      January  23.133333
Nebraska       NE      January  24.262500
Nevada         NV      January  32.820000
New Hampshire  NH      January  12.650000
New Jersey     NJ      January  33.366667
...                        ...        ...
Massachusetts  MA     December  31.800000
Michigan       MI     December  26.666667
Minnesota      MN     December  15.960000
Mississippi    MS     December  46.666667
Missouri       MO     December  33.950000
Montana        MT     December  22.666667
Nebraska       NE     December  25.500000
Nevada         NV     December  32.540000
New Hampshire  NH     December  18.450000
New Jersey     NJ     December  37.866667
New Mexico     NM     December  37.166667
New York       NY     December  32.700000
North Carolina NC     December  43.683333
North Dakota   ND     December  13.925000
Ohio           OH     December  31.475000
Oklahoma       OK     December  39.600000
Oregon         OR     December  37.075000
Pennsylvania   PA     December  33.025000
Rhode Island   RI     December  34.300000
South Carolina SC     December  48.525000
South Dakota   SD     December  19.750000
Tennessee      TN     December  40.816667
Texas          TX     December  48.314286
Utah           UT     December  29.050000
Vermont        VT     December  25.800000
Virginia       VA     December  40.425000
Washington     WA     December  35.728571
West Virginia  WV     December  35.275000
Wisconsin      WI     December  23.150000
Wyoming        WY     December  24.375000

[600 rows x 2 columns]

In [7]:
main_table.to_csv("Resources/weather_data.csv", index=True, header=True)